# AIFO Coder Toolchain Shim Implementation — v1 (Comprehensive Specification)

Status: Implemented
Owner: Toolchain/Proxy
Last updated: 2025-09-17

Scope
- This document specifies all shim implementations currently present in the aifo-coder system,
  their methodology, runtime selection precedence, signal and disconnect behavior, logging,
  configuration via environment variables, and pros/cons.
- “Shim” refers to the client-side entrypoints that forward tool invocations (cargo, npm, etc.)
  from the agent container to the in-process aifo-coder proxy, which then orchestrates execution
  in a dedicated toolchain sidecar container.

High-level architecture
- Inside the agent container, tools (cargo, rustc, npm, …) are provided as symlinks in /opt/aifo/bin
  that all point to a central aifo-shim client.
- The aifo-shim performs an HTTP POST to the local in-process aifo-coder proxy /exec endpoint, using
  streaming (chunked transfer), and obtains the final exit status via a response trailer header
  X-Exit-Code.
- The proxy translates the request into docker exec for the appropriate sidecar, using a small
  wrapper that runs the tool in its own process group (setsid) and records the process group id
  (PGID) for later signal delivery.
- On client disconnect or explicit signals, the proxy delivers INT → TERM → KILL to the recorded
  PGID in the sidecar. Additional best-effort steps are performed to terminate the transient shell
  spawned by the agent when the user used a “/run …” command.

Shim variants implemented today

1) Image-baked POSIX shell shim (default when no host override)
- Location in container:
  - /opt/aifo/bin/aifo-shim (script)
  - All tool commands are symlinks in /opt/aifo/bin pointing to aifo-shim
- Provisioned by:
  - Dockerfile (base and base-slim stages) using a RUN printf … block that writes the file content
- Methodology:
  - POSIX sh + curl streaming client for protocol v2
  - Posts to /exec and dumps response headers; parses X-Exit-Code from the dumped headers
  - Supports unix:// socket transport by mapping to curl’s --unix-socket and rewriting URL to
    http://localhost/exec
  - Minimal verbosity: prints “aifo-shim: tool=… cwd=…” and “preparing request …” when
    AIFO_TOOLCHAIN_VERBOSE=1
- Behavior:
  - No signal traps; a user Ctrl-C interrupts curl, which drops the HTTP stream; the proxy then
    performs disconnect cleanup and escalated signal delivery to the sidecar process group
  - No ExecId generation by the client; proxy generates an ExecId when absent
  - No per-exec marker files are written by this shim
- Pros:
  - Always present in images; very small; predictable behavior
- Cons:
  - No graceful /signal POST from client on Ctrl-C; relies on disconnect detection
  - No parent-shell termination; may expose “fall into agent shell” symptoms without additional
    mitigations
  - No disconnect-wait UX; logs may race the agent’s prompt redraw

2) Host-generated POSIX shell shim (feature-rich; mount via AIFO_SHIM_DIR)
- Generated by:
  - src/toolchain/shim.rs::toolchain_write_shims(dir)
- Typical usage:
  - Generate shims on the host into a directory
  - Launch agent with env AIFO_SHIM_DIR=/path/to/dir so docker run includes:
    -v /path/to/dir:/opt/aifo/bin:ro
- Files written into dir:
  - aifo-shim (script; main client)
  - Tool wrappers: cargo, rustc, node, npm, npx, tsc, ts-node, python, pip, pip3, gcc, g++, cc, c++,
    clang, clang++, make, cmake, ninja, pkg-config, go, gofmt, notifications-cmd — each execs
    "$(dirname "$0")/aifo-shim" "$@"
  - Shell wrappers: sh, bash, dash — auto-exit helpers (see below)
- Methodology:
  - POSIX sh + curl client for v2 with the following extras:
    - Adds X-Aifo-Exec-Id header using a generated or provided ExecId (AIFO_EXEC_ID)
    - Traps INT/TERM/HUP:
      - 1st Ctrl-C (INT): POST /signal INT; cleanup; optionally kill parent shell; exit
        (default ec=0; legacy ec=130 when AIFO_SHIM_EXIT_ZERO_ON_SIGINT=0)
      - 2nd Ctrl-C: POST /signal TERM; cleanup; optionally kill parent shell; exit (default 0 or 143)
      - 3rd Ctrl-C: POST /signal KILL; cleanup; optionally kill parent shell; exit (default 0 or 137)
    - Sends form payload using --data-urlencode for tool, cwd, and repeated arg=…
    - On unix:// URL, uses --unix-socket and http://localhost/exec
    - On disconnect (curl returns non-zero and no X-Exit-Code read):
      - Writes per-exec markers under $HOME/.aifo-exec/<ExecId>/:
        - pgid (written by sidecar wrapper; see proxy section)
        - agent_ppid, agent_tpgid, tty (recorded by shim)
        - no_shell_on_tty (flag used by shell wrappers to avoid lingering prompts)
      - In verbose mode (AIFO_TOOLCHAIN_VERBOSE=1), informs the user and delays exit:
        “aifo-coder: disconnect, waiting for process termination…”
        waits AIFO_SHIM_DISCONNECT_WAIT_SECS (default 1), then prints:
        “aifo-coder: terminating now” and an extra blank line to give the agent a clean prompt line
      - Optionally forces exit code 0 (AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT=1; default) or 1 otherwise
    - Attempts to terminate the transient parent shell on signal or disconnect:
      kill_parent_shell_if_interactive:
        - Determines PPID comm name (sh|bash|dash|zsh|ksh|ash|busybox|busybox-sh)
        - Sends HUP → TERM → KILL to PPID, and if PPID is a group leader, also to -PGID
        - Gated by AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT=1 (default)
- Shell wrappers (sh, bash, dash):
  - When invoked as sh -c/-lc "cmd" …, append "; exit" so shells terminate after the command
  - If interactive and controlling TTY matches a recent tool exec with “no_shell_on_tty” marker,
    the wrapper exits immediately (prevents dropping into an interactive shell)
- Logging:
  - aifo-shim: tool=… cwd=… exec_id=…
  - aifo-shim: preparing request to … (proto=2)
  - On disconnect (verbose): “disconnect, waiting …” then “terminating now”
- Pros:
  - Full signal UX: graceful /signal posting; deterministic closure of transient shells
  - Clear user messaging on disconnect; prompt-safe blank line on exit
  - Configurable behaviors via env vars; no image rebuild required when mounted from host
- Cons:
  - Requires host mount to override the baked shim (AIFO_SHIM_DIR)
  - Complex shell logic; best-effort process/tty identification

3) Rust aifo-shim binary (optional, not used by default image)
- Source:
  - src/bin/aifo-shim.rs
- Built by:
  - Dockerfile’s rust-builder stage (target/release/aifo-shim), but the current images overwrite
    /opt/aifo/bin/aifo-shim with the inline shell version; the Rust binary is not installed into
    the final images today
- Methodology:
  - Native Rust program that shells out to curl with v2 streaming
  - Adds X-Aifo-Exec-Id header (from env AIFO_EXEC_ID or generated)
  - Records per-exec markers under $HOME/.aifo-exec/<ExecId>/:
    - agent_ppid, agent_tpgid (parsed from /proc/self/stat), tty (readlink of fd 0 or 1)
  - On disconnect (no X-Exit-Code read):
    - Keeps marker dir for proxy to close transient shells
    - Optionally exits 0 unless AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT=0
    - In verbose mode (AIFO_TOOLCHAIN_VERBOSE=1), prints “disconnect, waiting …”, waits
      AIFO_SHIM_DISCONNECT_WAIT_SECS (default 1), then “terminating now” and a blank line
  - On successful completion (had headers), removes the marker dir
- Pros:
  - Easier to maintain and test than a large shell script; same UX improvements on disconnect
- Cons:
  - Not currently wired into the final images; still relies on curl
  - No POSIX signal traps (disconnect path + markers + proxy is relied on for termination)

Runtime selection and precedence

- By default, the agent container uses what is present inside the image:
  - /opt/aifo/bin/aifo-shim (the image-baked POSIX shell shim)
  - Tool symlinks to that aifo-shim
- If AIFO_SHIM_DIR is set on the host before launching the agent, docker.rs mounts that directory
  read-only at /opt/aifo/bin, overriding the baked files. In this mode, the host-generated shims
  (shell aifo-shim + wrappers) are active.
- The Rust aifo-shim binary is not currently used by default; to adopt it in images, the Dockerfile
  must COPY it into /opt/aifo/bin/aifo-shim and avoid overwriting it with the inline shell script.

Agent shell selection and prevention of “falling into a shell”
- The agent container’s SHELL is explicitly set to /opt/aifo/bin/sh (docker.rs), making transient
  shells prefer the wrapper installed there (when present).
- The wrapper forces auto-exit behavior after sh -c/-lc commands and uses the no_shell_on_tty marker
  to avoid lingering interactive prompts.
- Together with the proxy’s disconnect cleanup and shim’s parent-shell termination, this prevents
  post-Ctrl-C “drop into a shell” scenarios.

Proxy behavior (for completeness; not a shim but integral to signals/termination)
- Location: src/toolchain/proxy.rs
- ExecId registry: HashMap<ExecId, ContainerName> populated on /exec
- Streaming v2 prelude: includes X-Exec-Id header back to the client
- setsid wrapper in sidecar:
  - docker exec runs sh -c "setsid … exec <tool> …"
  - Writes PGID to $HOME/.aifo-exec/<ExecId>/pgid, then waits and cleans the dir on normal exit
- Disconnect handling (v2):
  - On write failure to the client, prints “aifo-coder: disconnect”
  - After ~150 ms grace (to allow shim /signal POST), delivers:
    INT, then after ~500 ms TERM, then after ~1.5 s KILL to -PGID in the sidecar
  - Best-effort closure of transient /run shell in the agent container:
    - Reads agent_ppid, agent_tpgid, and tty markers; HUP/TERM/KILL PPID and/or -PGID,
      and optionally injects “exit” and EOF to the controlling TTY
- Optional max-runtime escalation:
  - AIFO_TOOLEEXEC_MAX_SECS (or legacy AIFO_TOOLEEXEC_TIMEOUT_SECS) triggers a background watcher
  - Sends INT at T, TERM at T+5s, KILL at T+10s if the tool is still running
- TTY streaming:
  - AIFO_TOOLEEXEC_TTY=1 forces the proxy to allocate -t for docker exec to improve interactive
    flushing; default is not to allocate -t unless requested

Environment variables (relevant to shims and orchestration)

Client/shim-side:
- AIFO_TOOLEEXEC_URL: Proxy endpoint (http://host.docker.internal:<port>/exec or unix://…)
- AIFO_TOOLEEXEC_TOKEN: Bearer token to authorize calls
- AIFO_TOOLCHAIN_VERBOSE: “1” enables extra shim messages
- AIFO_EXEC_ID: Optional ExecId provided by the caller; otherwise generated by the shim
- AIFO_SHIM_EXIT_ZERO_ON_SIGINT: Default “1” → exit code 0 on INT/TERM/HUP traps; “0” → legacy 130/143/129
- AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT: Default “1” → return 0 when HTTP stream disconnects; “0” → return 1
- AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT: Default “1” → attempt to kill transient parent shell; “0” disables
- AIFO_SHIM_DISCONNECT_WAIT_SECS: Integer seconds to wait for proxy logs to flush on disconnect; default 1
- AIFO_SHIM_DIR (host): When set to a directory path, docker.rs mounts it at /opt/aifo/bin:ro,
  making host-generated shims active inside the agent container

Agent-container/launcher-side:
- SHELL: Set by docker.rs to /opt/aifo/bin/sh to prefer wrapper for transient shells
- AIFO_AGENT_IGNORE_SIGINT: Default “0”; when “1”, the container wrapper ignores SIGINT before exec
- PATH: docker.rs prepends /opt/aifo/bin and /opt/venv/bin when present

Proxy-side:
- AIFO_TOOLEEXEC_MAX_SECS: Optional max tool runtime (INT at T, TERM at T+5s, KILL at T+10s)
- AIFO_TOOLEEXEC_TIMEOUT_SECS: Legacy name for max runtime (same semantics)
- AIFO_TOOLEEXEC_TTY: “1” to allocate a TTY for docker exec streaming (improves flushing)
- AIFO_TOOLEEXEC_USE_UNIX (Linux): “1” to use a unix domain socket listener; mounted at /run/aifo
- AIFO_TOOLEEXEC_UNIX_DIR (Linux): Host socket directory used/mounted by the proxy
- AIFO_TOOLEEXEC_ADD_HOST (Linux): “1” to add host.docker.internal:host-gateway to sidecars for debugging

Exit code semantics and mapping (shell shim)
- INT/TERM/HUP traps:
  - Default: exit 0 to avoid dropping into interactive agent shells and to signal “user cancel” as
    a successful return to the agent
  - Legacy mode (AIFO_SHIM_EXIT_ZERO_ON_SIGINT=0): 130 for INT, 143 for TERM, 129 for HUP
- KILL trap (third Ctrl-C):
  - Default: exit 0; legacy: 137
- Disconnect (no X-Exit-Code read):
  - Default: exit 0; legacy: exit 1
- Normal completion:
  - Exit code is the numeric X-Exit-Code trailer value

Known behaviors and verification
- To verify the active shim inside an agent container:
  - echo "$SHELL" should print /opt/aifo/bin/sh (preferred wrapper)
  - head -n 40 /opt/aifo/bin/aifo-shim to view the active shim’s contents
  - If no “disconnect, waiting …” lines are present, you’re using the image-baked shim
  - In agent startup logs (aifo-coder --verbose), check for -v <host_shims>:/opt/aifo/bin:ro to
    confirm that host-generated shims are mounted

Pros and cons overview

Image-baked POSIX shell shim:
- Pros: Minimal, always present, simple and reliable streaming/exit-code handling
- Cons: No traps, no ExecId header, no disconnect-wait messaging, no parent-shell control

Host-generated POSIX shell shim:
- Pros: Feature-complete (traps, ExecId header, parent-shell termination, disconnect wait UX),
  plus sh/bash/dash wrappers to avoid lingering shells; quickly updatable without image rebuild
- Cons: Requires host mount to activate; larger shell logic

Rust aifo-shim binary:
- Pros: Maintainable, testable, same disconnect UX and markers; path to a native HTTP client
- Cons: Not installed in final images today; still shells out to curl; no POSIX traps

Recommended path forward (non-binding)
- Bake a compiled Rust aifo-shim into images at /opt/aifo/bin/aifo-shim (replace inline printf in
  Dockerfile), and include sh/bash/dash wrappers (from generator) in images so the SHELL wrapper
  is always available.
- Keep AIFO_SHIM_DIR mounting for developer overrides and rapid iteration.
- Optionally evolve the Rust shim to use a native HTTP client to remove curl dependency.

Appendix: Related proxy/sidecar details (for completeness)

- Sidecar exec wrapper (setsid):
  - Writes PGID to $HOME/.aifo-exec/<ExecId>/pgid inside sidecar
  - Waits for process completion; cleans the directory on normal exit
- Disconnect termination sequence:
  - INT, wait ~500 ms → TERM, wait ~1.5 s → KILL
  - Best-effort to kill agent /run shell using agent_ppid/agent_tpgid/tty markers; may also inject
    “exit” and EOF to the controlling TTY
- Streaming v2:
  - Responds with chunked transfer; includes Trailer: X-Exit-Code; prelude includes X-Exec-Id

This document reflects the current implementation and selection behavior of all shims in the
aifo-coder system, consolidating logic across shim scripts, the Rust shim, proxy, and docker wrapper.
