# AIFO Coder Toolchain Shim Implementation — v5
Production-ready unified Rust shim + baked shell wrappers, host override, native HTTP client,
and phased acceptance tests to freeze behavior at each milestone.

Status: In progress (v5.0 baked Rust shim + wrappers; v5.1 parity; v5.2 native HTTP; v5.3 hardening)
Owner: Toolchain/Proxy
Last updated: 2025-09-17

Executive summary
- v4 established the final direction: make a compiled Rust aifo-shim the default in images, bake
  sh/bash/dash wrappers that auto-exit transient shells, preserve the host override path with
  AIFO_SHIM_DIR, achieve full parity with the host POSIX shim (signals, markers, UX), and eliminate
  curl by implementing a native HTTP client.
- v5 makes this plan production-ready with precise Dockerfile requirements, consistent logging/UX,
  platform notes, exact environment knobs, acceptance tests for each phase, and rollback guidance.

Goals
- Authoritative default in images:
  - /opt/aifo/bin/aifo-shim is a compiled Rust binary.
  - /opt/aifo/bin/{sh,bash,dash} are auto-exit wrappers (scripts).
  - Tool symlinks under /opt/aifo/bin all exec aifo-shim.
- Full feature parity with host POSIX shim:
  - ExecId header (X-Aifo-Exec-Id) and per-exec markers ($HOME/.aifo-exec/<ExecId>/…).
  - Signal handling: INT/TERM/HUP → POST /signal with escalation (INT → TERM → KILL).
  - Parent-shell termination (Linux, best-effort).
  - Disconnect wait UX in verbose mode; unified verbose logging (include exec_id).
  - Exit code semantics aligned: 0 by default for traps/disconnect (legacy opt-in).
- Host override kept:
  - AIFO_SHIM_DIR overrides baked binary and wrappers by bind-mounting over /opt/aifo/bin:ro.
- Native HTTP roadmap:
  - Rust shim replaces curl with a built-in HTTP/1.1 client (TCP + Linux UDS), chunked transfer,
    tolerant trailers parsing (X-Exit-Code), and robust disconnect semantics.
- Production gates:
  - Each phase includes explicit acceptance tests with a minimal test harness invocation.

High-level architecture
- Inside the agent container, “tools” (cargo, npm, gcc, …) are symlinks to /opt/aifo/bin/aifo-shim.
- aifo-shim posts to the host aifo-coder proxy /exec (proto v2 streaming).
- Proxy runs on host (TCP or Linux UDS), wraps docker exec with setsid, records PGID to
  $HOME/.aifo-exec/<ExecId>/pgid in the sidecar, and performs disconnect/signal escalation to -PGID.
- Agent-side markers recorded by aifo-shim help the proxy terminate the transient “/run …” shell.
- Launcher sets SHELL=/opt/aifo/bin/sh in the agent container so transient shells use our wrapper.

Shim variants in v5

1) Image-baked Rust aifo-shim (default)
- Location in agent container:
  - /opt/aifo/bin/aifo-shim (ELF binary; authoritative).
  - /opt/aifo/bin/{cargo,rustc,node,npm,npx,tsc,ts-node,python,pip,pip3,gcc,g++,cc,c++,clang,
    clang++,make,cmake,ninja,pkg-config,go,gofmt,notifications-cmd} → symlinks to aifo-shim.
  - /opt/aifo/bin/sh, /opt/aifo/bin/bash, /opt/aifo/bin/dash → auto-exit wrappers (scripts).
- Provisioning (Dockerfile):
  - COPY --from=rust-builder /workspace/target/release/aifo-shim → /opt/aifo/bin/aifo-shim; chmod 0755.
  - Install wrapper scripts /opt/aifo/bin/sh, /opt/aifo/bin/bash, /opt/aifo/bin/dash with:
    - Auto-exit for -c/-lc “cmd; exit”.
    - Immediate exit when controlling TTY matches a recent tool exec with no_shell_on_tty marker.
  - Create tool symlinks to aifo-shim.
  - Keep curl in base images until v5.2 (native HTTP).
- Methodology (v5.0–v5.1 behavior):
  - v5.0: Rust shim shells out to curl (transitionary; native HTTP in v5.2).
  - Adds X-Aifo-Exec-Id (from env AIFO_EXEC_ID or generated).
  - Records markers:
    - agent_ppid, agent_tpgid (from /proc/self/stat), tty (readlink of fd 0/1),
    - no_shell_on_tty (flag checked by wrappers).
  - Verbose (AIFO_TOOLCHAIN_VERBOSE=1):
    - “aifo-shim: tool=<t> cwd=<p> exec_id=<id>”
    - “aifo-shim: preparing request to <url> (proto=2)”
  - Disconnect UX (no X-Exit-Code trailer):
    - “aifo-coder: disconnect, waiting for process termination…”
    - Sleep AIFO_SHIM_DISCONNECT_WAIT_SECS (default 1).
    - “aifo-coder: terminating now” and a final blank line for a clean prompt.
  - Exit code semantics:
    - Normal: trailer X-Exit-Code numeric.
    - Traps (default): exit 0 (AIFO_SHIM_EXIT_ZERO_ON_SIGINT=1; legacy non-zero if set to 0).
    - Disconnect: exit 0 by default (AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT=1; legacy 1 if set to 0).
  - v5.1 parity adds:
    - Signal hooks (INT/TERM/HUP) → POST /signal with escalation on repeated Ctrl-C.
    - Parent-shell termination on Linux (best-effort HUP/TERM/KILL PPID; also -PGID when PPID is
      group leader), gated by AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT=1.
    - Unified verbose lines including exec_id consistently with shell shim.

2) Host-generated POSIX shell shims (override path)
- Generated by: src/toolchain/shim.rs::toolchain_write_shims(dir).
- Activation: AIFO_SHIM_DIR points to dir; mount read-only at /opt/aifo/bin to override baked files.
- Contents: aifo-shim (curl client), tool wrappers, sh/bash/dash wrappers.
- Methodology: Full feature set (ExecId, /signal traps, markers, disconnect wait UX, wrappers).
- Pros: Rapid iteration; feature-complete today.
- Cons: Requires mount; depends on curl in container.

3) Legacy inline POSIX shim (removed in v5 images)
- The inline printf-based aifo-shim is removed from images (replaced by compiled Rust aifo-shim).

Proxy behavior (validated; docs aligned)
- Location: src/toolchain/proxy.rs.
- ExecId registry (HashMap<ExecId, ContainerName>) populated on /exec; v2 prelude includes X-Exec-Id.
- setsid wrapper: runs tool with new PGID; writes $HOME/.aifo-exec/<ExecId>/pgid; cleans on normal exit.
- Disconnect (stream write error):
  - eprintln “aifo-coder: disconnect” on a fresh line.
  - After ~150 ms grace, send INT; after ~500 ms, TERM; after ~1500 ms, KILL to -PGID.
  - Best-effort kill of transient “/run …” shell inside agent container using agent_ppid/agent_tpgid/
    tty markers; may also inject “exit” and EOF.
- Optional max runtime:
  - AIFO_TOOLEEXEC_MAX_SECS (legacy AIFO_TOOLEEXEC_TIMEOUT_SECS): INT at T, TERM at T+5s, KILL at T+10s.

Environment variables (shim-side; both shell and Rust)
- AIFO_TOOLEEXEC_URL: http://host.docker.internal:<port>/exec or unix://… (Linux).
- AIFO_TOOLEEXEC_TOKEN: Bearer token.
- AIFO_TOOLCHAIN_VERBOSE: “1” → extra shim messages and disconnect wait UX.
- AIFO_EXEC_ID: Optional; otherwise generated by shim.
- AIFO_SHIM_EXIT_ZERO_ON_SIGINT: default “1” (0 → legacy 130/143/129).
- AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT: default “1” (0 → legacy 1).
- AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT: default “1”.
- AIFO_SHIM_DISCONNECT_WAIT_SECS: integer seconds (default 1).
- AIFO_SHIM_DIR (host): mount to override /opt/aifo/bin (binary + wrappers).

Launcher behavior (agent container)
- SHELL=/opt/aifo/bin/sh ensures transient shells prefer the wrapper (auto-exit).
- PATH includes /opt/aifo/bin so tool symlinks resolve to aifo-shim.
- AIFO_CODER_CONTAINER_NAME exported for proxy’s best-effort agent-shell cleanup logic.

Exit code semantics (unified)
- Normal completion: numeric X-Exit-Code trailer.
- Traps (INT/TERM/HUP): default exit 0; legacy 130/143/129 when AIFO_SHIM_EXIT_ZERO_ON_SIGINT=0.
- Third Ctrl-C (KILL): default 0; legacy 137.
- Disconnect (no trailer): default 0; legacy 1 when AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT=0.

Dockerfile requirements (production)
- Remove inline printf-based aifo-shim script from all final images.
- COPY compiled Rust aifo-shim into /opt/aifo/bin/aifo-shim; chmod 0755.
- Install sh/bash/dash wrappers into /opt/aifo/bin; chmod 0755.
- Create tool symlinks in /opt/aifo/bin pointing to aifo-shim.
- Keep curl until v5.2 (native HTTP cutoff); then remove from slim images if unused elsewhere.

Unified logging (verbose)
- Shim:
  - aifo-shim: tool=<t> cwd=<p> exec_id=<id>
  - aifo-shim: preparing request to <url> (proto=2)
  - On disconnect: “aifo-coder: disconnect, waiting for process termination…”, “aifo-coder:
    terminating now”, then a blank line.
- Proxy:
  - aifo-coder: proxy parsed tool=… argv=… cwd=…
  - aifo-coder: docker: docker exec …
  - aifo-coder: proxy exec: proto=v2 (streaming)
  - aifo-coder: proxy result tool=<t> kind=<k> code=<c> dur_ms=<ms>

Phased implementation plan (optimized and testable)

Phase 1 — Bake-in (images + wrappers; curl-backed Rust shim)
- Deliverables:
  - Dockerfile installs compiled Rust aifo-shim to /opt/aifo/bin/aifo-shim (chmod 0755).
  - Dockerfile installs sh/bash/dash wrappers to /opt/aifo/bin (chmod 0755).
  - Tool symlinks under /opt/aifo/bin point to aifo-shim.
  - Launcher continues to set SHELL=/opt/aifo/bin/sh.
  - Keep curl in images (transitionary).
- Acceptance tests:
  - Container content:
    - file /opt/aifo/bin/aifo-shim → ELF executable (not a script).
    - head -n 20 /opt/aifo/bin/sh → wrapper with “; exit”.
    - PATH includes /opt/aifo/bin; SHELL=/opt/aifo/bin/sh.
  - Ctrl-C behavior:
    - /run cargo build → Ctrl-C returns to agent; does not drop into shell.
  - Host override:
    - With AIFO_SHIM_DIR set, -v <dir>:/opt/aifo/bin:ro is present; head -n 20 shows script shim.

Phase 2 — Rust parity with shell shim (signals + parent-shell + unified logs)
- Deliverables:
  - Rust shim supports signal hooks for INT/TERM/HUP using signal_hook (or equivalent).
  - First Ctrl-C → POST /signal INT; second → TERM; third → KILL; then exit (0 by default).
  - Honors AIFO_SHIM_EXIT_ZERO_ON_SIGINT (0 → legacy non-zero codes).
  - Implements parent-shell termination on Linux (best-effort) gated by AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT=1.
  - Verbose start line includes exec_id (matches shell shim).
- Acceptance tests:
  - Signal escalation:
    - Start long-running tool; press Ctrl-C once → proxy receives /signal INT; shim exits 0.
    - Press twice → TERM; thrice → KILL.
  - Parent shell not lingering:
    - After Ctrl-C, agent prompt returns on a clean line (no intermediate shell).
  - Logs:
    - aifo-shim start lines include exec_id; proxy logs show INT → TERM → KILL on disconnect.

Phase 3 — Native HTTP client (curl-free)
- Deliverables:
  - Rust shim implements HTTP/1.1 POST /exec with:
    - Transfer-Encoding: chunked request.
    - Trailer parsing for X-Exit-Code (tolerant CRLFCRLF/LFLF).
    - TCP client (default).
    - Linux UDS when AIFO_TOOLEEXEC_URL=unix://path with request target http://localhost/exec.
  - Remove curl from slim images if unused elsewhere.
- Acceptance tests:
  - TCP:
    - Streams large output; parses trailers; returns correct exit code.
  - UDS (Linux):
    - With AIFO_TOOLEEXEC_USE_UNIX=1 and unix socket mounted, native UDS path functions.
  - Disconnect behavior:
    - Mid-stream write error triggers disconnect wait UX and default exit code semantics.

Phase 4 — Hardening, test harness, and release
- Deliverables:
  - E2E tests:
    - Prompt cleanliness under Ctrl-C for multiple tools (cargo, npm, python).
    - Host override precedence: with/without AIFO_SHIM_DIR.
    - TCP and UDS transports on Linux; large-output stability.
    - Mixed sidecars running; correct tool-to-sidecar routing via proxy.
  - Documentation and release notes:
    - Images contain Rust aifo-shim + wrappers by default.
    - curl removed post Phase 3 (note any remaining dependencies).
    - How to verify active shim and override with AIFO_SHIM_DIR.
- Acceptance tests (frozen behavior):
  - Golden logs (selected lines) for verbose runs.
  - Exit-code mapping under INT/TERM/HUP and disconnect (default/legacy toggles).
  - No drop-into-shell regression across agents.

Test harness (how to run tests at each phase)
- Unit/integration tests (host):
  - cargo test
- Runtime smoke (requires Docker):
  - Aider (example):
    - ./aifo-coder aider --toolchain rust --verbose
    - In agent container, run: /run cargo build then Ctrl-C.
  - Verify:
    - “aifo-coder: disconnect” appears.
    - Shim prints disconnect-wait/terminating-now (verbose). Prompt returns cleanly.
- Host override checks:
  - Set AIFO_SHIM_DIR to a dir generated by toolchain_write_shims and re-run agent:
    - Verify mount -v <dir>:/opt/aifo/bin:ro present; behavior matches host-generated shim.

Risks and mitigations
- Prompt overwrite race:
  - Shim prints disconnect-wait + final blank line before exit (verbose).
- Lingering shells:
  - Baked wrappers + parent-shell termination + proxy best-effort cleanup.
- Curl dependency:
  - Retained until Phase 3; removed afterwards; track explicitly.
- Override precedence:
  - Documented; AIFO_SHIM_DIR wins; verify with log/preview and file checks in container.
- Platform variance:
  - UDS is Linux-only; default TCP everywhere; macOS/Windows host use TCP.

Rollout and rollback
- Rollout:
  - Phase-by-phase with acceptance gates; tag images per phase; prefer canary agent sessions first.
- Rollback:
  - Re-tag last known good image with inline shim if needed.
  - Set AIFO_SHIM_DIR to host-generated shims to bypass baked binary during investigation.

Appendix: Wrapper exact behavior
- sh/bash/dash wrapper:
  - If invoked as sh -c/-lc "cmd", executes "cmd; exit".
  - If interactive and controlling TTY matches $HOME/.aifo-exec/<ExecId>/tty with no_shell_on_tty,
    exits immediately.

Appendix: Parent-shell termination heuristic (Linux)
- Consider comm in {sh,bash,dash,zsh,ksh,ash,busybox,busybox-sh}.
- Avoid wide PGID kills unless PPID is group leader; keep sleeps brief (50–100 ms) between HUP/TERM/KILL.

This v5 specification finalizes a production-grade plan with crisp UX, unified logging, host override,
and a native HTTP roadmap, each phase validated by concrete acceptance tests and a lightweight test
harness, ensuring predictable behavior and safe rollout.
