# AIFO Coder Toolchain Shim Implementation — v3 (Unified Rust Shim + Shell Wrappers, Host Override, Native HTTP Roadmap)

Status: In progress (v3.0 baked Rust shim + wrappers; v3.1 parity; v3.2 native HTTP)
Owner: Toolchain/Proxy
Last updated: 2025-09-17

Executive summary
- v2’s direction was correct, but the live images/code diverged from the spec (inline POSIX shim, missing wrappers, curl dependency).
- v3 unifies behavior by baking a compiled Rust aifo-shim and sh/bash/dash wrappers into agent images, preserving host override via AIFO_SHIM_DIR, and delivering full feature parity (signals, markers, disconnect UX), then removing curl by moving to a native HTTP client.

Validation of v2 and current state
- Image content mismatch: Images still write an inline printf-based POSIX shell shim to /opt/aifo/bin/aifo-shim; the compiled Rust shim is not installed into final images.
- Missing wrappers: sh/bash/dash wrappers are not baked into images, weakening SHELL=/opt/aifo/bin/sh behavior.
- Rust shim gaps: It shells out to curl; lacks INT/TERM/HUP traps and /signal POST; does not attempt parent-shell termination; verbose logging not fully aligned.
- Proxy docs inconsistency: Module header claims TERM → KILL on disconnect while implementation performs INT → TERM → KILL (code is correct; comment is stale).
- Runtime selection: Host override with AIFO_SHIM_DIR is supported and functions; needs to be the authoritative dev/debug override path.

Corrections and decisions
- Make the compiled Rust aifo-shim the default in all agent images at /opt/aifo/bin/aifo-shim.
- Bake sh/bash/dash wrappers into images at /opt/aifo/bin with auto-exit and no_shell_on_tty behavior.
- Keep host override: When AIFO_SHIM_DIR is set, mount it at /opt/aifo/bin:ro to override all baked files (binary + wrappers).
- Continue setting SHELL=/opt/aifo/bin/sh from the launcher so transient shells prefer our wrapper.
- Bring Rust shim to parity with the host-generated shell shim (ExecId header; traps with /signal escalation; markers; parent-shell termination; disconnect UX).
- Migrate Rust shim away from curl by implementing a native HTTP client with TCP and Linux UDS support.

High-level architecture
- Tools in the agent container are symlinks under /opt/aifo/bin that exec /opt/aifo/bin/aifo-shim.
- Rust aifo-shim implements protocol v2 streaming; the proxy accepts /exec and streams tool output from a dedicated toolchain sidecar process group (setsid + PGID).
- On disconnect or /signal posts, the proxy delivers INT → TERM → KILL to the sidecar process group and uses agent-side markers to terminate transient “/run …” shells cleanly.

Shim variants in v3

1) Image-baked Rust aifo-shim (default)
- Location:
  - /opt/aifo/bin/aifo-shim (ELF binary)
  - /opt/aifo/bin/{cargo,rustc,node,npm,npx,tsc,ts-node,python,pip,pip3,gcc,g++,cc,c++,clang,clang++,make,cmake,ninja,pkg-config,go,gofmt,notifications-cmd} → symlinks to aifo-shim
  - /opt/aifo/bin/sh, /opt/aifo/bin/bash, /opt/aifo/bin/dash (auto-exit wrappers)
- Provisioning (Dockerfile):
  - COPY --from=rust-builder /workspace/target/release/aifo-shim → /opt/aifo/bin/aifo-shim; chmod 0755
  - Install wrapper scripts at /opt/aifo/bin; chmod 0755
  - Create tool symlinks → aifo-shim
- Methodology (v3.0):
  - curl-backed /exec POST (transitionary); X-Aifo-Exec-Id header; records markers: agent_ppid, agent_tpgid, tty, no_shell_on_tty.
  - Disconnect UX: If AIFO_TOOLCHAIN_VERBOSE=1, print:
    “aifo-coder: disconnect, waiting for process termination…”, then after AIFO_SHIM_DISCONNECT_WAIT_SECS (default 1), print:
    “aifo-coder: terminating now” followed by a blank line to give a clean prompt.
  - Exit code on disconnect: 0 by default (AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT=1), legacy 1 if set to 0.
- Parity (v3.1):
  - Signal hooks (INT/TERM/HUP) post /signal with escalation, defaulting to exit 0 (legacy codes via AIFO_SHIM_EXIT_ZERO_ON_SIGINT=0).
  - Parent-shell termination (Linux): best-effort HUP/TERM/KILL to PPID when it looks like a shell; also -PGID if PPID is group leader (guarded by AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT=1).
  - Unified verbose lines include exec_id.
- Native HTTP (v3.2):
  - Replace curl with a Rust HTTP/1.1 client (chunked transfer; Trailer: X-Exit-Code; tolerant header parsing).
  - Linux UDS: AIFO_TOOLEEXEC_URL=unix://path connects to socket and targets http://localhost/exec.

2) Host-generated POSIX shims (override)
- Generated by src/toolchain/shim.rs::toolchain_write_shims(dir): aifo-shim script, tool wrappers, and sh/bash/dash wrappers.
- Activated by AIFO_SHIM_DIR=/path (mounted read-only to /opt/aifo/bin).
- Behavior: Full feature set is already implemented (ExecId header, /signal traps and escalation, markers, disconnect UX, wrappers).

3) Legacy inline POSIX shim (removed)
- Inline aifo-shim created via printf in older images is removed in v3 images.

Runtime selection and precedence
- Default: compiled Rust aifo-shim + baked sh/bash/dash wrappers in /opt/aifo/bin.
- Host override: AIFO_SHIM_DIR mounted at /opt/aifo/bin:ro overrides all baked content.
- Launcher: SHELL=/opt/aifo/bin/sh ensures transient shells prefer our wrapper, which auto-exits.

Proxy behavior (validated)
- ExecId registry for running execs; v2 prelude includes X-Exec-Id.
- Sidecar wrapper: setsid + PGID recording at $HOME/.aifo-exec/<ExecId>/pgid; cleans on normal exit.
- Disconnect handling:
  - Prints “aifo-coder: disconnect”.
  - Sends INT (after ~150 ms grace), then TERM (~500 ms after INT), then KILL (~1500 ms after TERM) to -PGID.
  - Best-effort closure of the agent /run shell via agent_ppid/agent_tpgid/tty markers; may also inject “exit” and EOF.

Shell wrappers in images
- Behavior:
  - If invoked as sh -c/-lc "cmd" … → run “cmd; exit” to auto-terminate the shell after completion.
  - If interactive and controlling TTY matches a recent tool exec with no_shell_on_tty → exit immediately (prevents lingering prompts).
- SHELL=/opt/aifo/bin/sh ensures our wrapper is used by transient shells created by the agent.

Unified logging (verbose)
- From shim:
  - aifo-shim: tool=<t> cwd=<p> exec_id=<id>
  - aifo-shim: preparing request to <url> (proto=2)
  - On disconnect: “aifo-coder: disconnect, waiting for process termination…”, then “aifo-coder: terminating now”, then a blank line
- From proxy:
  - aifo-coder: proxy parsed tool=… argv=… cwd=…
  - aifo-coder: docker: docker exec …
  - aifo-coder: proxy exec: proto=v2 (streaming)
  - aifo-coder: proxy result tool=<t> kind=<k> code=<c> dur_ms=<ms>

Environment variables (shim-side; both shell and Rust)
- AIFO_TOOLEEXEC_URL: http://host.docker.internal:<port>/exec or unix://… (Linux).
- AIFO_TOOLEEXEC_TOKEN: Bearer token.
- AIFO_TOOLCHAIN_VERBOSE: “1” enables extra shim messages and disconnect wait UX.
- AIFO_EXEC_ID: Optional; otherwise generated by shim.
- AIFO_SHIM_EXIT_ZERO_ON_SIGINT: default “1” (exit 0 on INT/TERM/HUP); “0” for legacy 130/143/129.
- AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT: default “1” (exit 0 on disconnect); “0” for legacy 1.
- AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT: default “1”.
- AIFO_SHIM_DISCONNECT_WAIT_SECS: integer seconds (default 1).
- AIFO_SHIM_DIR (host): override /opt/aifo/bin.
- Agent launcher: SHELL=/opt/aifo/bin/sh; PATH includes /opt/aifo/bin; AIFO_CODER_CONTAINER_NAME exported.

Exit code semantics (unified)
- Normal completion: numeric X-Exit-Code from trailer.
- Traps (INT/TERM/HUP): default exit 0 (legacy codes with AIFO_SHIM_EXIT_ZERO_ON_SIGINT=0).
- Third Ctrl-C (KILL): default exit 0 (legacy 137).
- Disconnect (no header): default exit 0 (legacy 1 with AIFO_SHIM_EXIT_ZERO_ON_DISCONNECT=0).

Dockerfile requirements (v3)
- Remove inline printf-based aifo-shim.
- COPY compiled Rust aifo-shim into /opt/aifo/bin/aifo-shim; chmod 0755.
- Install sh/bash/dash wrappers (auto-exit + no_shell_on_tty).
- Create tool symlinks to aifo-shim.
- Keep curl until v3.2, then remove if unused elsewhere.

Consistency fixes
- Update proxy module header to state disconnect sequence INT → TERM → KILL (code already matches).
- Shim verbose lines include exec_id consistently (shell and Rust).
- Rust shim must honor AIFO_SHIM_EXIT_ZERO_ON_SIGINT and implement parent-shell termination (Linux).

Verification checklist
- No host override:
  - echo “$SHELL” → /opt/aifo/bin/sh
  - file /opt/aifo/bin/aifo-shim → ELF 64-bit executable
  - head -n 40 /opt/aifo/bin/sh → wrapper script with “; exit”
- Ctrl-C during run:
  - Shim prints disconnect-wait messaging and blank line; agent prompt returns; no lingering shell.
- Host override:
  - docker preview shows -v <host_shims>:/opt/aifo/bin:ro
  - head -n 40 /opt/aifo/bin/aifo-shim shows script version
- UDS (Linux): unix mode works (v3.0 via curl; v3.2 via native HTTP).

Risks and mitigations
- Prompt overwrite race: patched by shim disconnect wait + final blank line.
- Lingering shells: wrapped shells + parent-shell termination + proxy best-effort cleanup.
- Curl dependency: retained only until v3.2.
- Override precedence: preserved; AIFO_SHIM_DIR wins.

Comprehensive phased implementation plan

Phase 1 — Bake-in (images + wrappers; curl-backed Rust shim)
- Dockerfile:
  - COPY compiled Rust aifo-shim → /opt/aifo/bin/aifo-shim; chmod 0755.
  - Install sh/bash/dash wrappers into /opt/aifo/bin; chmod 0755.
  - Create tool symlinks to aifo-shim.
  - Keep curl packages.
- Launcher:
  - Keep SHELL=/opt/aifo/bin/sh.
- Acceptance tests:
  - Agent container shows ELF aifo-shim; wrappers present.
  - /run <tool> + Ctrl-C returns to agent; no drop into shells.

Phase 2 — Rust parity with shell shim
- Implement in Rust shim:
  - Signal hooks INT/TERM/HUP with /signal POST and escalation (INT → TERM → KILL).
  - Honor AIFO_SHIM_EXIT_ZERO_ON_SIGINT and legacy codes.
  - Parent-shell termination on Linux (PPID comm match; HUP/TERM/KILL; -PGID if leader; gated by AIFO_SHIM_KILL_PARENT_SHELL_ON_SIGINT=1).
  - Unified verbose lines including exec_id.
- Acceptance tests:
  - Ctrl-C once exits 0 (default) and posts INT; repeated Ctrl-C escalates.
  - Parent shell does not linger; agent prompt remains clean.

Phase 3 — Native HTTP client (curl-free)
- Replace curl with native HTTP/1.1 client:
  - POST /exec; chunked transfer; Trailer: X-Exit-Code; tolerant CRLFCRLF/LFLF.
  - Linux UDS: unix://path connect; http://localhost/exec target semantics.
- Dockerfile:
  - Remove curl in slim images if not needed elsewhere.
- Acceptance tests:
  - TCP and UDS streaming stable; exit code trailers parsed; disconnect behavior preserved.

Phase 4 — Hardening and release
- E2E tests: prompt cleanliness, override precedence, TCP/UDS, large output, multiple execs.
- Documentation: images now contain Rust shim + wrappers; curl removed after Phase 3.
- Keep AIFO_SHIM_DIR override documented and supported.

Appendix: Native HTTP client details (target)
- HTTP/1.1 client with chunked request/response.
- Trailer parsing (X-Exit-Code) with tolerant header boundary detection.
- UDS support via UnixStream on Linux; TCP fallback elsewhere.
- Signal path: signal_hook handlers post /signal as form (exec_id, signal).

This v3 spec resolves v2 inconsistencies by baking the Rust shim and shell wrappers into images, preserving host override, completing signal parity and prompt-safe UX, and eliminating curl via a native HTTP client under a clear, testable phased plan.
